salesforcecli/plugin-deploy-retrieve

bin/dev, package.json, src/commands/deploy.ts, yarn.lock
Uses new hook interface from [sf-plugins-core](https://github.com/salesforcecli/sf-plugins-core)
@W-9811480@
=> feat: use sf-plugins-core

package.json, src/commands/deploy.ts, yarn.lock
=> fix: bump to latest sf-plugins-core

src/commands/deploy.ts, yarn.lock
All deployers were being executed during a non-interactive deploy. This PR filters the deployers based on the saved configuration.
@W-9984183@
=> fix: filter deployers when executing non-interactive deploy

src/commands/deploy/metadata.ts
remove unnecessary default value for the `--tests` flag
=> fix: remove default value for tests

messages/deploy.metadata.md, messages/retrieve.metadata.md
Edits --help for `sf deploy|retrieve metadata` after support for metadata format was added. 
@ W-11722878@
=> edit messages for deploy|retrieve in md format

test/nuts/seeds/deploy.metadata.manifest.seed.ts, test/nuts/seeds/deploy.metadata.metadata-dir.seed.ts, test/nuts/seeds/deploy.metadata.metadata.seed.ts, test/nuts/seeds/deploy.metadata.test-level.seed.ts
Adds `{ cli: 'sfdx' }` to external command executions so that just-nuts will pass
=> chore: update external command executions

test/nuts/seeds/deploy.metadata.manifest.seed.ts
fix this: https://github.com/salesforcecli/cli/actions/runs/3534492111/jobs/5931424087
by specifying which CLI to use for assigning permissionSets (sfdx, the only one that currently can do that)
=> test: specify cli for permet-assign

messages/deploy.metadata.md
Mostly aligns the "client timeout" error with a sister DevOps message.  
@W-12520652@
=> fix: minor edits to "sf deploy metadata" messages

messages/convert.mdapi.md, messages/convert.source.md, messages/delete.source.md, messages/deploy.async.md, messages/deploy.md, messages/deploy.metadata.cancel.md, messages/deploy.metadata.md, messages/deploy.metadata.preview.md, messages/deploy.metadata.report.md, messages/deploy.metadata.resume.md, messages/list.ignored.md, messages/manifest.create.md, messages/retrieve.metadata.md, messages/retrieve.metadata.preview.md, src/commands/project/deploy/cancel.ts, src/commands/project/deploy/quick.ts, src/commands/project/deploy/report.ts, src/commands/project/deploy/resume.ts, src/commands/project/deploy/start.ts, src/commands/project/deploy/validate.ts, src/commands/project/list/ignored.ts, src/commands/project/retrieve/start.ts, src/formatters/asyncDeployCancelResultFormatter.ts, src/formatters/asyncDeployResultFormatter.ts, src/utils/deploy.ts
fixes hardcoded `sf` references in messages.  
replaced with `config.bin`
Also includes various other edits to the messages files. 
[skip-validate-pr] - found in blitz
=> fix: replace hardcoded 'sf' with config.bin for sfdx use

package.json, test/nuts/digitalExperienceBundle/deb.tracking.nut.ts, test/nuts/digitalExperienceBundle/helper.ts, test/nuts/list/ignored.nut.ts, test/tsconfig.json, tsconfig.json, yarn.lock
1. correct several mistakes on nut paths that are causing problem for SDR xNuts
2. remove tsconfig paths settings.  These can be re-added for local yarn-link but should stay out of the build process, for more flexibility for xNuts.
=> chore: correct relative paths, remove tsconfig paths

src/commands/project/delete/source.ts, src/commands/project/deploy/resume.ts, src/commands/project/deploy/start.ts, src/commands/project/deploy/validate.ts, src/utils/deploy.ts
sdr doesn't provide good typing for deploy.id (it's a couple layers of inheritance with a getter that's marked as string | undefined.
rather than adding more complexity (and likely a breaking change) to sdr types, any consumer using strict types must handle the ambiguous typing.
A better long-term solution would be to use generics on the layers above sdr/metadataTransfer (ie, metadataApiDeploy|Retrieve and componentSet.deploy|retrieve) to make it clear when the id is set [when it's passed in, when start has already been called] vs not.
@W-12671663@
=> refactor: handle undefined deployId

test/nuts/digitalExperienceBundle/helper.ts
Corrects the expectation for preview command when DigitalExperience component files are added/deleted/changed. 
**preview** command shows the metafile path, unlike the **status** command showing individual content file paths.
[@W-12965438@](https://gus.lightning.force.com/a07EE00001OS9AAYA1)
=> test: expect metafile path for preview command

messages/deploy.metadata.md, messages/deploy.metadata.preview.md, messages/retrieve.metadata.md, messages/retrieve.metadata.preview.md
Clarifies that the --no-track-source flag mentioned in the help is on "org create scratch|sandbox", not the "project deploy" commands.
@W-13106710@
=> fix: clarify the --no-track-source mention in the help

src/utils/coverage.ts, test/utils/coverage.test.ts
@W-13048665@
The `mapTestResults` method is used by [`DeployResultFormatter`](https://github.com/salesforcecli/plugin-deploy-retrieve/blob/9e79c4024cdf75078c95ce8bcc0c449e31363561/src/formatters/deployResultFormatter.ts#L153) to map the nested test-results of a deployment-result into `ApexTestResultData` objects, which are later used to generate a JUnit test report. Commit https://github.com/salesforcecli/plugin-deploy-retrieve/commit/cdc8f6e615f4cfa9c5accaf6c420bc2333258c78 introduces a bug which is mapping test results without a `message` property to a failed test and vice versa. 
This PR switches the logic back to the original one.
https://github.com/forcedotcom/cli/issues/2076
This is a JSON example for a succeeded test retrieved via deploy API:
```json
{
"namespace" : null,
"name" : …
```
=> fix: testresult mapping of source deployment

messages/deploy.metadata.md, messages/deploy.metadata.validate.md
help referred to `--run-tests`, which doesn't exist. Correct flag name is `--tests`
@W-13260780@
=> fix: wrong flag name

src/formatters/deployResultFormatter.ts
handle null stacktrace
[@W-13481008@](https://gus.lightning.force.com/a07EE00001SBsUJYA1)
https://github.com/forcedotcom/cli/issues/2149
=> fix: stacktrace can by null (is typed wrong)

src/formatters/deployResultFormatter.ts, test/utils/output.test.ts
prints errors reported by the server that were missed from `.getFileResponses`
before
```
➜  ../../oss/plugin-deploy-retrieve/bin/dev project:deploy:start                                                     
*** Deploying with SOAP API v57.0 ***
Deploy ID: 0AfDR00002Z1Q1i0AF
Status: Failed | ████████████████████████████████████████ | 3/3 Components
```
after
```
➜  ../../oss/plugin-deploy-retrieve/bin/dev project:deploy:start
*** Deploying with SOAP API v57.0 ***
Deploy ID: 0AfDR00002Z1Rxo0AF
Status: Failed | ████████████████████████████████████████ | 3/3 Components
Component Failures [1]
===================================================================
| Type  Name                               Problem                  
| ───── ────────────────────────────────── …
```
=> fix: print errors from server

messages/deploy.metadata.md, messages/retrieve.start.md, src/commands/project/deploy/cancel.ts, src/commands/project/deploy/quick.ts, src/commands/project/deploy/report.ts, src/commands/project/deploy/resume.ts, src/commands/project/deploy/start.ts, src/commands/project/deploy/validate.ts, src/commands/project/retrieve/start.ts, src/utils/output.ts
This changes the various deploy and retrieve commands to listen to the event fired from the SDR library to output the correct sourceApiVersion and apiVersion used when making those requests.  There are certain scenarios where the plugin doesn't have all the necessary data at the appropriate time to handle it and display a correct message.
NOTE: this changes some of the commands to not report the apiVersion message because they are only polling for results or using a jsforce API directly.  The commands are: `deploy quick`, `deploy report`, and `deploy resume`.  These commands are simply reporting or continuing deploy requests that were already made so displaying the apiVersion message is not super important.
@W-13223973@
=> fix: display correct api version

src/formatters/deployResultFormatter.ts, test/utils/deployResponses.ts, test/utils/output.test.ts
will create UT output directories even when running with `--json`
@W-13505809@
https://github.com/forcedotcom/cli/issues/2172
=> fix: respect UT flags when running with json

package.json, src/commands/project/deploy/quick.ts, src/utils/deploy.ts, test/commands/deploy/metadata/quick.nut.ts
When a `--metadata-dir --dry-run` deploy was subsequentally `deploy quick`'d it would fail when creating a component set to print the results for
the `componentSet` parameter was optional where it was used, so removed need for a CS when `deploy quick`
@W-13131279@
https://github.com/forcedotcom/cli/issues/2098
=> fix: allow mdapi --dry-runs to be quick deploy'd if valid

messages/deploy.metadata.validate.md, src/commands/project/deploy/validate.ts, src/formatters/deployResultFormatter.ts, test/utils/deployResponses.ts, test/utils/output.test.ts
warns the user when the deployment doesn't meet the required code coverage
before
```
➜  sf project deploy validate --source-dir force-app/main/default --test-level RunAllTestsInOrg          
Validating Deployment of v57.0 metadata to test-2dkeausn14hp@example.com using the v57.0 SOAP API.
Deploy ID: 0Af5300000e2PMyCAM
Status: Failed | ████████████████████████████████████████ | 87/87 Components
Test Results Summary
Passing: 0
Failing: 0
Total: 0
Error (1): Failed to validate the deployment (0Af5300000e2PMyCAM).
```
after
```
➜  sf project:deploy:validate --source-dir force-app --test-level RunAllTestsInOrg
Validating Deployment of v57.0 metadata to test-2dkeausn14hp@example.com using the v57.0 SOAP API.
Deploy ID: 0Af5300000e2RDiCAM
Status: Failed | …
```
=> fix: warn when code coverage doesn't meet requirement

messages/retrieve.start.md, src/commands/project/retrieve/start.ts
Removes API version from spinner msg in `project retrieve start` command.
=> fix: remove API version from spinner

package.json, src/commands/project/retrieve/start.ts, test/nuts/delete/source.nut.ts, test/nuts/retrieve/metadata.nut.ts, test/nuts/seeds/deploy.metadata.manifest.seed.ts, test/nuts/seeds/deploy.metadata.metadata-dir.seed.ts, test/nuts/seeds/deploy.metadata.metadata.seed.ts, test/nuts/seeds/deploy.metadata.test-level.seed.ts, yarn.lock
allows `project retrieve start --package-name` to retrieve packages in the org
@W-13472911@
https://github.com/forcedotcom/cli/issues/2148
=> test: add --package-name NUTs, remove sfdx cli referecnes

.husky/pre-push, command-snapshot.json, messages/delete.source.md, messages/deploy.metadata.validate.md, schemas/hooks/sf-deploy.json, src/commands/project/delete/source.ts, src/commands/project/deploy/validate.ts, src/formatters/deleteResultFormatter.ts, src/formatters/deployResultFormatter.ts, src/formatters/testResultsFormatter.ts, src/utils/flags.ts, src/utils/output.ts, test/nuts/delete/source.nut.ts
Adds support for running specific tests when deleting metadata via `--test-level RunSpecifiedTests --tests <tests`.
https://github.com/forcedotcom/cli/issues/2175
@W-13510661@
=> feat: allow to run specific tests on source delete

src/commands/project/deploy/cancel.ts, src/utils/deploy.ts
`project deploy cancel` command no longer requires a project.
@W-13608500@
https://github.com/forcedotcom/cli/issues/2224
=> fix: project not required for canceling

src/commands/project/deploy/quick.ts, src/commands/project/deploy/report.ts, src/commands/project/deploy/resume.ts, src/commands/project/deploy/validate.ts
In certain scenarios, when using `--metadata-dir` the `project deploy validate` command doesn't require a project, but `requiresProject=true` so it would throw an error
remove that line so it can be executed outside of a project
@W-13721102@
https://github.com/forcedotcom/cli/issues/2275
```bash
➜  ../oss/plugin-deploy-retrieve/bin/dev project deploy validate --metadata-dir temp --async --target-org test-iyv4subkohvd@example.com 
Validating Deployment of vundefined metadata to test-iyv4subkohvd@example.com using the v58.0 SOAP API.
Deploy ID: 0AfDH00001iUqjP0AS
Deploy has been queued.
Run "sf project deploy resume --job-id 0AfDH00001iUqjP0AS" to resume watching the deploy.
Run "sf project deploy report --job-id 0AfDH00001iUqjP0AS" to get the latest status.
Run "sf project deploy cancel …
```
=> fix: deploy validate doesn\'t require a project

messages/delete.source.md, src/commands/project/delete/source.ts
Makes `project delete source` throw an error if the user answers `no` when asking for confirmation.
```
➜  dreamhouse-lwc git:(main) echo no | sf project delete source --metadata ApexClass:GeocodingService
?
This operation will delete the following files on your computer and in your org:
/Users/cdominguez/code/gh/dreamhouse-lwc/force-app/main/default/classes/GeocodingService.cls-meta.xml
/Users/cdominguez/code/gh/dreamhouse-lwc/force-app/main/default/classes/GeocodingService.cls
Are you sure you want to proceed? No
Error (1): Cannot read properties of undefined (reading 'response')
```
```
➜  dreamhouse-lwc git:(main) echo no | ../sf/plugin-deploy-retrieve/bin/dev project:delete:source --metadata ApexClass:GeocodingService
?
This operation will delete the following files on your computer …
```
=> fix: throw if delete request is canceled

src/commands/project/deploy/validate.ts
add useful data to json error
https://github.com/forcedotcom/cli/issues/2312
@W-13765229@
=> feat: add deployId for output json of failed validate

package.json, test/nuts/delete/source.nut.ts, test/nuts/destructive/destructiveChanges.nut.ts, test/nuts/tracking/forceIgnore.nut.ts, yarn.lock
> requires https://github.com/salesforcecli/cli-plugins-testkit/pull/539
templates goes to v59, but the org might not support it for a few weeks.
This sets the api version on the created classes and the testkit project sourceApiVersion
[@W-13913391@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001XvsAqYAJ/view)
kinda caused by our rollout of [@W-13586057@](https://gus.lightning.force.com/a07EE00001Tl80JYAR)
example of the problem this solves: https://github.com/salesforcecli/cli/actions/runs/5804183268/job/15734000727
=> test: nuts that can run on v59

src/commands/project/deploy/validate.ts
Groups the flags in "project deploy validate" in the same was as they are grouped in "project deploy start", for consistency and user friendliness
@W-13907820@
=> fix: group flags in validate the same as in "start"

package.json
Updates the text when user uses `--help` flag on `generate` topics. 
It was:
> Commands to create a manifest file.
To be updated to: 
> Commands to create file artifacts, such as a project or manifest file.
Discussed with @mshanemc in public Slack workspaace.  [@W-14051727@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001ZmCcBYAV/view)
=> Update prompt help for generate topic

src/commands/project/deploy/quick.ts
Display the deploy ID of the quick deploy request, not the validation request.
@W-14094679@
=> fix: display deploy ID not validation ID

package.json, src/utils/previewOutput.ts, src/utils/types.ts, test/utils/types.test.ts, yarn.lock
existing code was allowing `xml: undefined` to match the SourceComponent type, but it doesn't really.  Then other code that expected a SC would throw unexpectedly
found during QA of https://github.com/forcedotcom/source-deploy-retrieve/pull/1093
@W-14138121@
=> fix: disallow undefined xml

messages/deploy.metadata.report.md, messages/deploy.metadata.resume.md, src/commands/project/deploy/quick.ts, src/commands/project/deploy/resume.ts, src/utils/deploy.ts, test/commands/deploy/metadata/resume.nut.ts
A completed deployment can now be resumed.  Also removes the `poll` function since SDR's `pollStatus` should be used instead.
@W-14149965@
QA:
`sf project deploy resume` should display the deploy results from already completed deployments rather than throwing an error.
=> fix: support resuming completed deployments

command-snapshot.json, messages/deploy.metadata.md, messages/deploy.metadata.quick.md, src/commands/project/deploy/report.ts, src/formatters/deployReportResultFormatter.ts, src/formatters/deployResultFormatter.ts, test/commands/deploy/metadata/report-mdapi.nut.ts, test/commands/deploy/metadata/report.nut.ts
Adds an optional `--target-org` and `--wait` flag to the `project deploy report` command.  This allows checking and polling for a deploy status of a targeted org without the need for cached deploy data.
@W-14053314@
https://github.com/forcedotcom/cli/discussions/2300
QA:
do an async deploy, then:
1. project deploy report --job-id {async deploy ID}
2. project deploy report --job-id {async deploy ID} --target-org {non-default org} 
3. project deploy report --job-id {async deploy ID} --target-org {non-default org} --wait 10
4. delete `deploy-cache.json`, then project deploy report --job-id {async deploy ID} --target-org {non-default org} --wait 10
5. force a timeout by doing a large deploy with a short wait time on the report command.  Ensure the command returns the status and not a timeout …
=> fix: adds target-org and wait support to deploy report command

messages/delete.tracking.md, src/commands/project/delete/tracking.ts, src/commands/project/reset/tracking.ts
Adds examples to project delete|reset tracking.  Previously "reset" had an example of querying SourceMember only, which was confusing.  Also fixed a lingering mention of "force:source". 
@W-14191974@
=> fix: add examples to project reset|delete tracking

messages/deploy.metadata.md, src/commands/project/deploy/start.ts, src/commands/project/deploy/validate.ts, src/commands/project/retrieve/start.ts, src/utils/deploy.ts
1. use `--api-version` flag on mdapi deploys
2. api message indicates that manifest controls the sourceApiVersion for mdapi deploys
[@W-14209534@](https://gus.lightning.force.com/a07EE00001bTEuoYAG)
=> fix: api version for mdapi deploys

package.json, src/formatters/deployResultFormatter.ts, test/utils/output.test.ts, yarn.lock
> requires https://github.com/forcedotcom/source-deploy-retrieve/pull/1130
- show col/line numbers on component fails
- sort the failures table better
- remove duplicate failure reporting
https://github.com/forcedotcom/cli/issues/356
@W-14247072@
=> feat: col, line numbers on mdapi deploy errors

src/commands/project/deploy/quick.ts, test/commands/deploy/metadata/quick.nut.ts
Changes quick deploy to use the new deploy ID and not the validation ID.  Augments NUTs to ensure this behavior.
@W-14481091@
https://github.com/forcedotcom/cli/issues/2537
=> fix: quick deploy polling uses the new deploy ID

src/formatters/deployResultFormatter.ts
Displays componentFailures that are not already captured with the file responses of the `DeployResult`.
@W-14470146@
https://github.com/forcedotcom/cli/issues/2561
=> fix: also display errors from componentFailures

package.json, test/nuts/convert/mdapi.nut.ts, test/nuts/convert/source.nut.ts, yarn.lock
Assert that failed exit codes are `nonZero` instead of `1`. Should fix `just-nuts` in nightly release
=> test: assert nonZero exit codes

LICENSE.txt, package.json, src/commands/project/delete/source.ts, yarn.lock
the linter caught this one...kicking off promises in an map but not handling the rejection possibility.
https://github.com/forcedotcom/eslint-config-salesforce-typescript/actions/runs/7390437279/job/20105358348?pr=210#step:9:9
=> refactor: floating-promises

src/commands/project/delete/source.ts
https://github.com/forcedotcom/eslint-config-salesforce-typescript/actions/runs/7391718156/job/20132526357?pr=210
=> fix: return the promise array

src/utils/deploy.ts, test/nuts/deploy/metadata.nut.ts
Update empty component set check to not cast deploy opts from `boolean | undefined` to `boolean` when using the `??` operator. 
It was changed to casting + `??` operator here:
https://github.com/salesforcecli/plugin-deploy-retrieve/pull/799/commits/ad2cb256e720565c5ad963068110c902605121a8#diff-38ace718cac3391d646985bcdd7fd17d4114a116432f5c6846db797b46552080R157
So if you don't pass these flags these are `undefined` at runtime, then casted to boolean so the `??` op will always return `false` unless the flag was specified.
Repro:
1) clone dreamhouse & create scratch org
2) create `package.xml` with this content:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
<version>59.0</version>
</Package>
```
3) try deploy using latest (below I'm …
=> fix: don't cast opts to boolean

command-snapshot.json, messages/deploy.metadata.preview.md, src/commands/project/deploy/preview.ts, test/nuts/tracking/forceIgnore.nut.ts
NOTE: same as #873 but updates the test to be correct.
What does this PR do?
Adds flag --concise to project deploy preview to skip displaying ignored files.
I saw this implementation and thought it was an oversight to only include it as part of the retrieve command and not deploy. https://github.com/salesforcecli/plugin-deploy-retrieve/pull/831
I also noticed the flag doesn't have a description, although I'm not sure if one is needed.
@W-14818332@
=> feat: add concise flag to deploy preview

package.json, yarn.lock
Bump to latest versions of SDR and STL to get a fix for the IdentityVerificationProcDev metadata type.
=> fix: bump SDR and STL

messages/diagnostics.md, package.json, src/hooks/diagnostics.ts, test/hooks/diagnostics.test.ts, yarn.lock
Copies doctor diagnostic tests from plugin-source to plugin-deploy-retrieve
@W-15000658@
=> fix: add doctor diagnostic test from plugin-source

messages/deploy.metadata.md, messages/deploy.metadata.validate.md, messages/retrieve.start.md
Added a useful tidbit about --ignore-warnings that I saw on Slack.  While I was at it, I improved some examples, something that had been bugging me for a while. 
@W-15162713@
=> fix: improve messages

messages/deploy.metadata.quick.md, messages/deploy.metadata.validate.md
Adds a note about note using the `validate` and `quick` commands on sandboxes
INV - [@W-15142351@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-15142351)
=> Sandbox note on validate and quick

messages/deploy.metadata.report.md, src/commands/project/deploy/report.ts, test/nuts/deploy/report.nut.ts
allows you to `deploy report` on a successful deployment
@W-15426325@
=> fix: allow deploy report on validated deploys

package.json, src/commands/project/convert/mdapi.ts, src/utils/deploy.ts, src/utils/flags.ts, src/utils/previewOutput.ts, test/nuts/convert/mdapi.nut.ts, test/nuts/convert/source.nut.ts, test/nuts/digitalExperienceBundle/helper.ts, test/nuts/specialTypes/folderTypes.nut.ts, yarn.lock
interface => type (2)
make no-param-reassign happier
I left one in the `retrieve start` command where it's modifying fileReponses inside SDR (!) because that's intentional and it'll be a larger, QA-worthy refactor to not do that 
I just exempted the whole DEB nut helper from the rule because...
https://github.com/forcedotcom/sfdx-core/actions/runs/8574106147/job/23500290588?pr=1046#step:12:9
=> fix: refactor interface=>type, no-param-reassign

test/nuts/deploy/runningTests.nut.ts
verify that the scenario described in the gh issue works fine on gha
https://github.com/forcedotcom/cli/issues/2834
=> test: nut for multiple --tests using gha

src/commands/project/delete/source.ts, src/utils/previewOutput.ts, src/utils/types.ts, test/utils/types.test.ts
This bug happens when you use `delete` command with a remote-only piece of metadata.  The confirmation prompt throws an error. 
change how we determine "is it a sourceComponent?" so we don't get an unsafe walkContent() access.
[I tried to create a NUT for this but the interactive command framework won't allow commands with spaces in them, will resolve that separately in testkit]
https://github.com/forcedotcom/cli/issues/2836
[@W-15572525@](https://gus.lightning.force.com/a07EE00001pgYPIYA2)
=> fix: missing walkContent on delete prompt

messages/convert.source-behavior.md, package.json
Edits the messages for the new "project convert source-behavior" command.
@W-15829280@
=> fix: edit the messages for "project convert source-behavior"

messages/convert.mdapi.md, messages/convert.source.md, messages/delete.source.md, messages/delete.tracking.md, messages/deploy.async.md, messages/deploy.metadata.cancel.md, messages/deploy.metadata.md, messages/deploy.metadata.preview.md, messages/deploy.metadata.quick.md, messages/deploy.metadata.report.md, messages/deploy.metadata.resume.md, messages/deploy.metadata.validate.md, messages/list.ignored.md, messages/manifest.generate.md, messages/retrieve.metadata.preview.md, messages/retrieve.start.md, src/commands/project/deploy/cancel.ts, src/commands/project/deploy/quick.ts, src/commands/project/deploy/resume.ts, src/commands/project/deploy/start.ts, src/commands/project/deploy/validate.ts, src/commands/project/retrieve/start.ts, src/formatters/asyncDeployCancelResultFormatter.ts, src/formatters/asyncDeployResultFormatter.ts, src/utils/deploy.ts
removing a lot of config.bin from messages.  Not needed anymore since we don't publish `sfdx`
@W-15867611@
=> fix: remove dynamic bin

messages/deploy.metadata.md, messages/retrieve.start.md
Adds examples to deploy and retrieve metadata with a namespace
https://github.com/forcedotcom/cli/issues/2875
[@W-15810307@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-15810307)
=> Add namespaced deploy-retrieve examples

messages/deploy.metadata.md, messages/deploy.metadata.preview.md, messages/deploy.metadata.quick.md, messages/deploy.metadata.validate.md, messages/retrieve.metadata.preview.md, messages/retrieve.start.md, package.json, src/commands/project/deploy/cancel.ts, src/commands/project/deploy/preview.ts, src/commands/project/deploy/quick.ts, src/commands/project/deploy/report.ts, src/commands/project/deploy/start.ts, src/commands/project/deploy/validate.ts, src/commands/project/retrieve/preview.ts, src/commands/project/retrieve/start.ts, yarn.lock
[no intended functionality change]
use the shared char/summary/description from the sf-plugins-core orgFlags
[@W-15895601@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001slw9jYAA/view)
=> fix: use standard target-org flag messages

messages/convert.mdapi.md, messages/convert.source.md, messages/delete.source.md, messages/delete.tracking.md, messages/deploy.metadata.cancel.md, messages/deploy.metadata.md, messages/deploy.metadata.preview.md, messages/deploy.metadata.quick.md, messages/deploy.metadata.report.md, messages/deploy.metadata.resume.md, messages/deploy.metadata.validate.md, messages/list.ignored.md, messages/manifest.generate.md, messages/retrieve.metadata.preview.md, messages/retrieve.start.md
we agreed that config.bin in help was maybe useful
followup to @W-15867611@
=> docs: restore some config.bin for --help stuff

test/nuts/convert/decompose.nut.ts
skip a few tests while I figure out how to best un-singletonify sfProject
=> test: skip most source-behavior nuts

messages/retrieve.start.md, src/commands/project/delete/source.ts, src/formatters/deleteResultFormatter.ts
update the warning message
https://github.com/forcedotcom/cli/issues/1366
@W-15983735@
=> docs: message for custom fields wildcard

messages/deploy.metadata.md, src/commands/project/deploy/start.ts, test/nuts/destructive/destructiveChanges.nut.ts
allows a user to specify `--purge-on-delete --metadata-dir...` 
as long as the specified metadata-dir has a destructive manifest in it, it will be deleted, and reported, and removed from recycling
@W-16010166@
=> fix: allow purge-on-delete with mdapi dirs

src/commands/project/deploy/validate.ts
appends test failure info to `project deploy validate` error message in `--json`
https://github.com/forcedotcom/cli/issues/2952
@W-16198239@
=> fix: append test info to validate error

src/commands/project/convert/mdapi.ts, test/nuts/convert/mdapi.nut.ts
Fix a bug where `project convert mdapi --output-dir path/to/output` would save the converted metadata to `path` instead of `path/to/output` if the path didn't exist before.
When the dir doesn't exist we create it for the user but the code was returning `fs.promises.mkdir` response which only returned the first dir in the path:
https://nodejs.org/api/fs.html#fspromisesmkdirpath-options
Updated convert NUT to check that the filepath starts with the full output path.
@W-15097291@
=> fix: use full output-path on `convert mdapi`

messages/retrieve.start.md, src/commands/project/retrieve/start.ts, src/formatters/retrieveResultFormatter.ts, test/commands/retrieve/start.test.ts
Updates the help text and command output for package-name flag to make it clear that it's for reference only and not intended for development use.
@W-16449733@
=> fix: clarify help docs and command output for package-name flag

package.json, test/commands/deploy/metadata/report.nut.ts, test/commands/deploy/metadata/resume.nut.ts, test/commands/deploy/metadata/validate.nut.ts, test/nuts/seeds/deploy.metadata.manifest.seed.ts, test/nuts/seeds/deploy.metadata.metadata.seed.ts, test/nuts/seeds/deploy.metadata.source-dir.seed.ts, yarn.lock
fix some tests from bumping testkit (SDR failure types)
to ship @W-16540802@
=> fix(deps): bump-sdr-for-new-types

src/utils/deployStages.ts
Prevent `NaN%` from showing in stage output by not showing source tracking progress is there are no source members. Also added a `if` statement in `formatProgress` to avoid dividing by 0
=> fix: prevent NaN in stage output

src/commands/project/convert/source.ts
make the default value to be static value only in the help text
@W-10067032@
=> fix: default hep value

schemas/project-deploy-cancel.json, schemas/project-deploy-quick.json, schemas/project-deploy-report.json, schemas/project-deploy-resume.json, schemas/project-deploy-start.json, schemas/project-deploy-validate.json, src/commands/project/deploy/quick.ts, src/commands/project/deploy/resume.ts, src/commands/project/deploy/start.ts, src/commands/project/deploy/validate.ts, src/utils/deploy.ts, src/utils/types.ts
The goal of this PR is to add Deploy URLs after the Deploy ID is printed in all project deploy commands. 
This is my first contribution period to a Salesforce repo, please let me know if I'm doing something wrong. This seemed like a simple update to add based on the `OrgConfigProperties` class from sfdx-core, but I'm not sure if there's something I missed when I'm trying to use this to get the org instance URL.
This will print the Classic URL, but we can update this to Lightning if that's preferred.
I know in at least GitLab CI/CD, just printing a valid URL in the pipeline log as I do in my Python script will create a clickable link. But if there's an explicit method in Typescript that can build a clickable link in all cases, I'm open to suggestion. …
=> feat: build deploy URL using ID

src/commands/project/deploy/resume.ts
Adds deploy url to resume command output and json
@W-16972065@
=> fix: deploy url in resume

package.json, src/commands/project/convert/source-behavior.ts, src/formatters/deleteResultFormatter.ts, src/formatters/deployReportResultFormatter.ts, src/formatters/deployResultFormatter.ts, src/formatters/metadataConvertResultFormatter.ts, src/formatters/retrieveResultFormatter.ts, src/formatters/testResultsFormatter.ts, src/utils/conflicts.ts, src/utils/previewOutput.ts, test/nuts/tracking/forceIgnore.nut.ts, test/utils/output.test.ts, yarn.lock
Use new table in sf-plugins-core v12
@W-16736188@
=> feat: use new table

src/commands/project/retrieve/start.ts
Handle scenario where MultiStageOutput hasn't been instantiated.
https://github.com/forcedotcom/cli/issues/3078
@W-17060314@
=> fix: ms might be undefined

test/nuts/tracking/forceIgnore.nut.ts
Use regex when asserting table output in nuts so that slight changes in table spacing doesn't cause failures
=> test: use regex when asserting table output

src/formatters/deployResultFormatter.ts, test/utils/output.test.ts
```bash
┌───────┬─────────────────────────────┬──────────────────────────────────────────────────────────────────────────────────┬─────────────┐
│ Type  │ Name                        │ Problem                                                                          │ Line:Column │
├───────┼─────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────┼─────────────┤
│ Error │ Broker__c-Broker Layout     │ Invalid field:Address__c in related list:Property__c.Broker__c                   │             │
│ Error │ Create_property             │ field integrity exception: unknown (The field "Address__c" for the object 
```
rather than displaying every error in the error table as an error, show what metadata type has the error, 
```bash …
```
=> fix: repurposes 'error' column, to show the metadata type

src/commands/project/delete/source.ts, test/commands/delete/source.test.ts
if you `project delete source` on something that's forceignored, you can have a bad time
this makes you have less of a bad time, prints a warning
@W-17013213@
=> fix: add warning when nothing to delete

src/commands/project/deploy/start.ts
Sometimes MSO would receive the final update from SDR _after_ the table was written to the terminal. This changes ensures that MSO is always stopped before the table is rendered.
=> fix: prevent duplicate MSO after table

.github/workflows/onRelease.yml, package.json, yarn.lock
Temporarily disable ctc and bump versions of STL and SDR.
=> fix: disable ctc and bump lib versions

src/commands/project/deploy/start.ts, src/formatters/deployResultFormatter.ts, src/formatters/testResultsFormatter.ts, test/utils/output.test.ts
Updates test formatters to always print apex test reports unless the caller doesn't want to.
This fixes a regression introduced [in this PR](https://github.com/salesforcecli/plugin-deploy-retrieve/pull/1215) where commands were missing the `Test Failures` report on CI runs of commands like `project deploy report`.
@W-17758238@
=> fix: always render apex test reports W-17758238

src/commands/project/retrieve/start.ts, test/commands/retrieve/start.test.ts
Agents can be retrieved using the Bot API name (as a pseudo-type).
@W-17043234@
=> W-17043234 - fix: support retrieving agent pseudo type

src/commands/project/retrieve/start.ts, test/nuts/retrieve/metadata.nut.ts
Fixes `project retrieve start --output-dir lala` writing single-file components to `lala/main/default` instead of `lala`.
1. SDR does the retrieve, there's no local components to merge with so it writes them to `<output-dir>/main/default`
2. `project retrieve start` checks if SDR retrieved files, if so then moves them from `<output-dir>/main/default` to `<output-dir` and nukes `main/default`.
The bug was in step 2, the command was skipping the file move if less than 2 files were retrieved (leaving single-file components like `GlobalValueSet` in `<output-dir>/main/default`.
1. clone dreamhouse and create a scratch org
2. create a globalvalueset in the org: `sf org open -p lightning/setup/Picklists/home` 
3. retrieve it to `lala`, see it being written to `lala/main/default`: `sf project …
=> fix: handle single file components move to output-dir W-17615754

package.json, test/nuts/manifest/manifestCreate.nut.ts, yarn.lock
The pinned SDR was causing the "long windows path check" to fail on the CLI release
The `apiVersion` change in the NUTs is because dreamhouse updated this version 9 hours ago (2025-02-20): https://github.com/trailheadapps/dreamhouse-lwc/blame/main/sfdx-project.json#L12
[@W-17875018@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-17875018)
=> W-17875018 bump deps to fix CLI releases

package.json, src/commands/project/retrieve/start.ts, test/commands/retrieve/start.test.ts, yarn.lock
Uses the `rootTypesWithDependencies` RetrieveRequest param when agent pseudotype is used with at least api version 64.0.
@W-17238293@
=> feat: use the rootTypesWithDependencies RetrieveRequest param - W-17238293

messages/retrieve.start.md
Provide an example of how to retrieve all list views for an object.  Warn about using `.*` as a wildcard matching pattern.
@W-18369903@
=> fix: update retrieve doc for .* wildcard retrieval - W-18369903

package.json, src/utils/convertBehavior.ts, yarn.lock
=> fix: bump libs

messages/metadata.transfer.md
fixes an error thrown by our messages parser when looking for a new message
'Finalizing' state message present
no errors
needs a 258 OrgFarm org on greater than CL 53818728
@W-19029417@
=> fix: for W-19029417 - fix finalzing MDAPI state W-19029417

package.json, schemas/project-delete-source.json, schemas/project-deploy-cancel.json, schemas/project-deploy-quick.json, schemas/project-deploy-report.json, schemas/project-deploy-resume.json, schemas/project-deploy-start.json, schemas/project-deploy-validate.json, schemas/project-retrieve-start.json, yarn.lock
Bump SDR to get new Rule type and other fixes, see SDR changelog since v12.21.1:
https://github.com/forcedotcom/source-deploy-retrieve/blob/main/CHANGELOG.md
Command schemas changed because the metadata API added a new supported state:
https://github.com/forcedotcom/source-deploy-retrieve/pull/1585
=> fix: bump SDR
