salesforcecli/plugin-deploy-retrieve

package.json
src/commands/deploy.ts
yarn.lock

Use SfCommand as base class for commands
@W-9791511@

fix: use sfcommand as base class

---

package.json
yarn.lock

fix: bump functions to 1.0.0

---

command-snapshot.json
messages/deploy.metadata.md
messages/metadata.transfer.md
messages/required.flag.md
messages/retrieve.metadata.md
package.json
schemas/deploy-metadata.json
schemas/hooks/sf-deploy.json
schemas/retrieve-metadata.json
src/commands/deploy/metadata.ts
src/commands/retrieve/metadata.ts
src/hooks/deploy.ts
src/utils/componentSetBuilder.ts
src/utils/config.ts
src/utils/metadataDeployer.ts
src/utils/orgs.ts
src/utils/output.ts
src/utils/progressBar.ts
src/utils/requiredFlagValidator.ts
src/utils/testLevel.ts
test/commands/deploy.nut.ts
test/commands/deploy/metadata.nut.ts
test/commands/retrieve/metadata.nut.ts
test/utils/componentSetBuilder.test.ts
yarn.lock

Moves the commands from plugin-deploy-retrieve-metadata into this plugin.
@W-10686184@

feat: merge deploy-retrieve-metadata commands

---

package.json

Removes nut tests running in parallel
w/o parallel nuts run in half the time.
@W-0@

chore: no parallel for test nuts

---

messages/deploy.metadata.md

Edits/adds --help content to new flags
@W-10749111@

review messages for new flags, first pass

---

src/commands/deploy/metadata.ts
src/commands/retrieve/metadata.ts

Mark `deploy metadata` and `retrieve metadata` as beta

feat: mark metadata commands as beta

---

package.json
src/utils/output.ts
yarn.lock

Bump version sf-plugins-core 
@W-0@

fix: bump sf—plugins-core

---

package.json
src/utils/progressBar.ts
yarn.lock

Depends on https://github.com/salesforcecli/sf-plugins-core/pull/57
@W-10877276@

fix: only call start once

---

package.json
src/utils/metadataDeployer.ts
yarn.lock

Use `StateAggregator` instead of `GlobalInfo`
Depends on https://github.com/forcedotcom/sfdx-core/pull/587
@W-11214501@

feat: use StateAggregator

---

test/nuts/tracking/constants.ts

Updates ebikes pushed items count for recent updates https://github.com/trailheadapps/ebikes-lwc/pull/419
Loosely tied to [@W-11358405@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-11358405)

Fix: ebikes nuts fix

---

messages/deploy.metadata.md
messages/deploy.metadata.preview.md
messages/previewMessages.md
messages/retrieve.metadata.preview.md

Edit/review messages for new "sf deploy|retrieve metadata preview" commands
@ W-11518739@

Edit/review messages for new "sf deploy|retrieve metadata preview" commands

---

messages/deploy.metadata.md
messages/deploy.metadata.preview.md
messages/deploy.metadata.validate.md
messages/previewMessages.md
messages/retrieve.metadata.preview.md

Final editorial review of preview messages.
@ W-11518739@

Edit preview messages

---

src/utils/previewOutput.ts

one map, if/else for diff comparison

refactor: one map, with more if else return {}

---

README.md
package.json
yarn.lock

[@W-12085135@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-12085135)

Parking orbit cleanup

---

.github/workflows/test.yml
src/commands/deploy.ts

remove oclif flag imports
@W-11824616@

refactor: remove oclif flags

---

src/commands/project/deploy/resume.ts
src/commands/project/deploy/validate.ts
src/formatters/deployResultFormatter.ts
src/utils/progressBar.ts

validate async doesn't wait for the whole deploy to happen

refactor: validate --async returns immediately

---

command-snapshot.json
messages/deploy.metadata.report.md
src/commands/project/deploy/report.ts

remove 2 unnecessary flags from report

fix: remove 2 flags from report

---

messages/deploy.metadata.md
src/commands/project/deploy/report.ts
src/commands/project/deploy/resume.ts
src/commands/project/deploy/start.ts
src/formatters/deployResultFormatter.ts
src/utils/manifestCache.ts
test/commands/deploy/start.test.ts
test/utils/manifestCache.test.ts

WR blitz fixes

---

package.json

Updates topic desc in package.json for correct --help and CLI Command Ref
@W-12565029@

fix: upate package.json for correct help and command ref

---

package.json
src/commands/project/deploy/report.ts
yarn.lock

Bump the latest version of STL, SDR, and core.
@W-00000000@

fix: bump SDR and core libs

---

package.json
yarn.lock

bump SDR to get fix for manifest create command, see: https://github.com/forcedotcom/source-deploy-retrieve/pull/941
@W-13056201@

fix: bump SDR

---

messages/delete.source.md

removes bad example
@W-13106710@

fix: remove bad sample

---

src/commands/project/deploy/start.ts
src/commands/project/retrieve/start.ts

flag groups for commands that have a LOT of flags
@W-13313150@

feat: flag groups for deploy/retrieve

---

package.json
yarn.lock

bump `@salesforce/core` to match SDR and rebuild the lockfile.
@W-00000000@

fix: bump core version and rebuild lock file

---

DEVELOPING.md

adds a `DEVELOPING.md` to go mirror plugin-packaging
@W-12980758@

docs: add developing.md

---

src/utils/progressBar.ts

Change progress bar default to show rather than detect support as default.
@W-13701811@
https://github.com/forcedotcom/cli/issues/2276
https://github.com/forcedotcom/cli/issues/2249

fix: default to showing the progress bar

---

package.json
yarn.lock

fix: Sh/bump sdr to 9.3.2

---

test/nuts/retrieve/partialBundleDelete.nut.ts

What does this PR do?
update partial bundle delete tests for Dreamhouse source changes

fix: update partial bundle delete tests for Dreamhouse source changes

---

src/commands/project/deploy/start.ts
src/commands/project/deploy/validate.ts

fix how --wait default value is defined so the command reference picks it up correctly
@W-14002266@

fix: change wait default value definition

---

src/formatters/retrieveResultFormatter.ts

shows retrieve warnings like plugin-source did
https://github.com/forcedotcom/cli/issues/2405
@W-14085256@

fix: show retrieve warnings in a table

---

package.json
test/nuts/tracking/constants.ts
yarn.lock

compensate for SDR changes
PR fix or reference?
https://github.com/forcedotcom/source-deploy-retrieve/actions/runs/6549455042/job/17786488963
@W-14262002@

test: deduped file responses

---

package.json
schemas/hooks/sf-deploy.json
yarn.lock

bump to latest SDR and STL to get fixes for CustomObjectTranslations
@W-13193003@

fix: bump sdr and stl

---

package.json
test/nuts/seeds/deploy.metadata.metadata-dir.seed.ts
test/nuts/seeds/deploy.metadata.source-dir.seed.ts
yarn.lock

https://github.com/salesforcecli/cli/actions/runs/7217237476/job/19665011286
https://github.com/salesforcecli/cli/actions/runs/7217237476/job/19665011373

test: non-zero exitCodes

---

package.json

fix(deps): ts-types as a real dep

---

test/commands/retrieve/start.test.ts
test/utils/deployResponses.ts

test: use structuredClone

---

test/nuts/tracking/constants.ts
test/nuts/tracking/remoteChanges.nut.ts
yarn.lock

ebikes removed 2 files
https://github.com/trailheadapps/ebikes-lwc/pull/649/files#diff-df6b944748317c72500f189cb37b829f24b3091e79593047d2b6ebf5eb3006fc
https://github.com/forcedotcom/source-deploy-retrieve/actions/runs/7891542653/job/21536184416?pr=1218

test: ebikes removed 2 files

---

package.json
yarn.lock

Bump SDR to 10.5.3 and STL to 5.1.18

Sh/bump sdr 10.5.3

---

command-snapshot.json
package.json
test/commands/delete/source.test.ts
yarn.lock

plugins-core8 and newer oclif
rollout for [@W-15285609@](https://gus.lightning.force.com/a07EE00001mY1q0YAC)

feat: support for flags-dir

---

src/commands/project/delete/source.ts

fix: remove logging

---

package.json
yarn.lock

fix(deps): bump apex-node off of beta

---

messages/manifest.generate.md

Improves help for --include-packages flag of "project create manifest"
@W-15664964@

fix: update help for --include-packages

---

package.json
yarn.lock

fix(deps): bump sdr

---

package.json
yarn.lock

fix: bump stl for logger bug

---

package.json
yarn.lock

fix: bump core to 8.0.3

---

test/nuts/seeds/deploy.metadata.metadata.seed.ts
yarn.lock

test failures on https://github.com/forcedotcom/source-deploy-retrieve/pull/1374 
are because the nut specifies the error name, which SDR is changing.
https://github.com/forcedotcom/source-deploy-retrieve/actions/runs/10081843723/job/27874888122?pr=1374
[@W-16324102@](https://gus.lightning.force.com/a07EE00001xOHgbYAG)

test: reove error name assertion

---

package.json
yarn.lock

fix(deps): bump apex lib

---

package.json
yarn.lock

fix: bump SDR [skip-validate-pr]

---

src/utils/coverage.ts
test/utils/coverage.test.ts

fixes code coverage results
@W-16822712@

fix: fix generated code coverage result percent

---

messages/convert.mdapi.md
messages/convert.source.md
messages/delete.source.md
messages/delete.tracking.md
messages/deploy.metadata.md
messages/deploy.metadata.preview.md
messages/deploy.metadata.validate.md
messages/manifest.generate.md
messages/retrieve.start.md

Fixes help for various commands that said you could specify --manifest more than once -- you can't. 
@W-17008080@

fix: you can't specify --manifest more than once

---

src/formatters/testResultsFormatter.ts

Add Apex test runtime to HRO
@W-17674281@

feat: W-17674281 - Add runtime to apex test method

---

package.json
yarn.lock

Needed for AnalyticsDashboard in the registry
[@W-17899278@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-17899278)

W-17899278 bump sdr for analytics-dashboard

---

package.json
yarn.lock

bumps SDR for double retrieve DEB fix
@W-18057369@

fix: bump SDR W-18057369

---

package.json
yarn.lock

Bumps SDR to get new DAM types into `sf`
@W-18422782@

fix: bump SDR W-18422782

---

src/formatters/testResultsFormatter.ts
test/nuts/deploy/verbose.nut.ts

Add test successes even when CI=true
@W-18531727@

fix: add test successes to verbose CI output - W-18531727

---

package.json
yarn.lock

Bump to the latest SDR to get the updated metadata registry.

fix: bump libs

---

package.json
test/nuts/retrieve/partialBundleDelete.nut.ts
yarn.lock

Bumps sfdx-core and resolves compilation error in NUTs caused by this change: https://github.com/forcedotcom/sfdx-core/commit/9c369a481d586b397f1e76ca467cc688586b2cc7

fix: bump sfdx-core

---

messages/metadata.transfer.md

What does this PR do?
adds new state from server to deploy status type
What issues does this PR fix or reference?
@W-19159018@

fix: add new deploy status W-19159018

---

package.json
yarn.lock

Bump core dependency to 8.19.1
@W-19327351@

fix: bump core dependency - W-19327351
